# Generated by Django 4.2.29 on 2026-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.TextField(help_text='Paste a YouTube link (watch, Shorts, youtu.be) or the full iframe embed code.')),
                ('youtube_id', models.CharField(blank=True, editable=False, max_length=11)),
                ('is_short', models.BooleanField(default=False, editable=False, help_text='Detected automatically from Shorts URLs.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery / Update',
                'verbose_name_plural': 'Gallery / Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
